# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=32, max_digits=34, unique=True, verbose_name='latitude')),
                ('lon', models.DecimalField(decimal_places=32, max_digits=35, unique=True, verbose_name='longitude')),
                ('geohash', models.CharField(max_length=32, verbose_name='geohash')),
            ],
        ),
    ]
