# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import geofield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', geofield.fields.GeoPositionField(db_index=True, max_length=32)),
            ],
        ),
    ]
